In [121]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [68]:
df_train = pd.read_csv('train.csv')
df_test = pd.read_csv('test.csv')

In [69]:
df_train.head()

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Fat_Content_LF,Item_Fat_Content_Low Fat,Item_Fat_Content_Regular,Item_Fat_Content_low fat,Item_Fat_Content_reg,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,6.800000,0.037490,48.6034,2004,291.6204,0,1,0,0,0,...,0,0,1,0,1,0,0,1,0,0
1,15.600000,0.172597,114.8518,1997,2163.1842,0,1,0,0,0,...,0,0,1,1,0,0,0,1,0,0
2,12.911575,0.054721,107.8254,1985,2387.5588,0,1,0,0,0,...,0,1,0,0,0,1,0,0,0,1
3,11.800000,0.098312,81.4618,1998,161.1236,0,1,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,17.850000,0.046600,125.1388,2004,1981.4208,0,0,1,0,0,...,0,0,1,0,1,0,0,1,0,0

In [70]:
df_train.shape

(1364, 36)

In [111]:
train_X = df_train.drop(columns=['Item_Outlet_Sales','Outlet_Establishment_Year'],axis=1)
train_y = df_train['Item_Outlet_Sales']

In [112]:
train_X.head()

,Item_Weight,Item_Visibility,Item_MRP,Item_Fat_Content_LF,Item_Fat_Content_Low Fat,Item_Fat_Content_Regular,Item_Fat_Content_low fat,Item_Fat_Content_reg,Item_Type_Baking Goods,Item_Type_Breads,...,Outlet_Size_High,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 1,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Grocery Store,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,6.800000,0.037490,48.6034,0,1,0,0,0,1,0,...,0,0,1,0,1,0,0,1,0,0
1,15.600000,0.172597,114.8518,0,1,0,0,0,0,0,...,0,0,1,1,0,0,0,1,0,0
2,12.911575,0.054721,107.8254,0,1,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
3,11.800000,0.098312,81.4618,0,1,0,0,0,0,0,...,0,0,0,0,0,1,1,0,0,0
4,17.850000,0.046600,125.1388,0,0,1,0,0,0,0,...,0,0,1,0,1,0,0,1,0,0

In [113]:
test_X = df_test.drop(columns=['Item_Outlet_Sales','Outlet_Establishment_Year'],axis=1)
test_y = df_test['Item_Outlet_Sales']

# LinearRegression

In [114]:
from sklearn.linear_model import LinearRegression

In [115]:
lr = LinearRegression()

In [116]:
lr.fit(train_X,train_y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [117]:
preds_y = lr.predict(test_X)

In [118]:
from sklearn.metrics import mean_squared_error

In [130]:
mean_squared_error(test_y,preds_y)

1010628.1302445631

In [149]:
import pickle

In [160]:
filename = 'finalized_model.sav'
pickle.dump(lr, open(filename, 'wb'))